"""post 1

Revision ID: 512fc19d16b6
Revises: 83f2bb60a07d
Create Date: 2021-03-15 21:50:43.228807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '512fc19d16b6'
down_revision = '83f2bb60a07d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=60), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('can_comment', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_post_timestamp'), 'tbl_post', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbl_post_timestamp'), table_name='tbl_post')
    op.drop_table('tbl_post')
    # ### end Alembic commands ###
